version: '3.8'
services:
  app:
    build: 
      context: ./S1
      dockerfile: Dockerfile
    stdin_open: true  
    tty: true         
    ports:
      - "5000:5000"
    depends_on:
      - hsm
  volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem

  hsm:
    build: 
      context: ./S2
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./cert.pem:/app/cert.pem
      - ./key.pem:/app/key.pem
